# Generated by Django 4.1.5 on 2023-02-22 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0002_banner_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner_area',
            name='Link',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
