# Generated by Django 4.1.5 on 2023-02-22 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0004_category_main_category_sub_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub_category',
            name='main_category',
        ),
    ]
