# Generated by Django 4.1.5 on 2023-03-07 00:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app4', '0011_dealsproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='accounts/order/image')),
                ('products', models.CharField(default='', max_length=1000)),
                ('Full_Name', models.CharField(max_length=20, null=True)),
                ('phone', models.CharField(max_length=10, null=True)),
                ('pincode', models.CharField(max_length=6, null=True)),
                ('City', models.CharField(max_length=10, null=True)),
                ('state', models.CharField(max_length=15, null=True)),
                ('address', models.TextField()),
                ('size', models.CharField(max_length=20, null=True)),
                ('price', models.IntegerField()),
                ('Quantity', models.CharField(max_length=5, null=True)),
                ('total', models.CharField(default='', max_length=1000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
