# Generated by Django 4.1.5 on 2023-03-07 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0012_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Full_Name',
            new_name='First_Name',
        ),
        migrations.AddField(
            model_name='order',
            name='Last_Name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
