# Generated by Django 4.1.5 on 2023-03-07 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0013_rename_full_name_order_first_name_order_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='packing_cost',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='tax',
            field=models.IntegerField(null=True),
        ),
    ]
