# Generated by Django 4.1.5 on 2023-03-08 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0016_remove_dealsproduct_discount_recommended_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommended_product',
            name='Tags',
        ),
        migrations.RemoveField(
            model_name='recommended_product',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='recommended_product',
            name='color',
        ),
    ]
