# Generated by Django 4.1.5 on 2023-03-11 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0019_mobile_computer_laptops'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Quantity',
        ),
        migrations.RemoveField(
            model_name='order',
            name='image',
        ),
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.RemoveField(
            model_name='order',
            name='size',
        ),
    ]
