# Generated by Django 4.1.5 on 2023-03-11 09:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0020_remove_order_quantity_remove_order_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
    ]
