# Generated by Django 4.1.5 on 2023-03-11 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0021_order_date_order_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total',
            new_name='amount',
        ),
    ]
