# Generated by Django 4.1.5 on 2023-03-11 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0024_alter_order_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='City',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='First_Name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='Last_Name',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='pincode',
            new_name='postcode',
        ),
    ]
