# Generated by Django 4.1.5 on 2023-03-13 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0026_order_image_order_products'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
