# Generated by Django 4.1.5 on 2023-03-14 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0028_order_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
    ]
