# Generated by Django 4.1.5 on 2023-03-22 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app4', '0029_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laptops',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='laptops',
            name='section',
        ),
        migrations.RemoveField(
            model_name='mens_fasion',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='mens_fasion',
            name='section',
        ),
        migrations.RemoveField(
            model_name='mobile_computer',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='mobile_computer',
            name='section',
        ),
        migrations.RemoveField(
            model_name='recommended_product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='recommended_product',
            name='section',
        ),
        migrations.RemoveField(
            model_name='womens_fasion',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='womens_fasion',
            name='section',
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='DealsProduct',
        ),
        migrations.DeleteModel(
            name='Laptops',
        ),
        migrations.DeleteModel(
            name='Mens_Fasion',
        ),
        migrations.DeleteModel(
            name='Mobile_Computer',
        ),
        migrations.DeleteModel(
            name='Recommended_Product',
        ),
        migrations.DeleteModel(
            name='Womens_Fasion',
        ),
    ]
