# Generated by Django 4.1.5 on 2023-03-23 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0030_remove_laptops_brand_remove_laptops_section_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='special_offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/specialOffer_img')),
                ('name', models.CharField(max_length=100)),
                ('Discount', models.IntegerField()),
                ('Link', models.CharField(default='', max_length=200, null=True)),
            ],
        ),
    ]
