# Generated by Django 4.1.5 on 2023-03-23 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0031_special_offer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='special_offer',
            old_name='Discount',
            new_name='price',
        ),
    ]
