# Generated by Django 4.1.5 on 2023-03-24 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0032_rename_discount_special_offer_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='First_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
