# Generated by Django 4.1.5 on 2023-03-24 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0034_smartphone'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartPhone_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=100)),
                ('smartphone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app4.smartphone')),
            ],
        ),
    ]
