# Generated by Django 4.1.5 on 2023-03-27 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0035_smartphone_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smartphone',
            old_name='product_name',
            new_name='smartphone_name',
        ),
    ]
