# Generated by Django 4.1.5 on 2023-04-03 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0039_alter_wishlist_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='smartphone',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='app4.smartphone'),
        ),
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
