# Generated by Django 4.1.5 on 2023-04-03 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0040_product_smartphone_delete_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smartphone',
            old_name='feature_image',
            new_name='phone_image',
        ),
        migrations.AlterModelTable(
            name='smartphone',
            table='app4_SmartPhone',
        ),
    ]
