# Generated by Django 4.1.5 on 2023-04-11 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0043_largban_area_banner_area_name_alter_orderitem_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner_area',
            name='name',
        ),
        migrations.RemoveField(
            model_name='largban_area',
            name='Discount_Deal',
        ),
        migrations.AddField(
            model_name='largban_area',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
